routes/web.php
<?php


Auth::routes();

// Home routes
Route::get('/', 'HomeController@index')->name('home');
Route::get('kurslar', 'HomeController@courses')->name('courses');
Route::get('kurs/{tutorial}', 'HomeController@course')->name('course');
Route::get('home/emailSub', 'HomeController@emailSub')->name('home.emailSub');

/* Dev Panel Routes */
Route::get('dev', 'DevController@index')->name('dev.index');

// Dev Tutorial Routes
Route::resource('dev/tutorial', 'Dev\TutorialController');
Route::post('tutorial/updatePos', 'Dev\TutorialController@updatePos')->name('tutorial.updatePos');

// Dev Module Routes
Route::resource('dev/module', 'Dev\ModuleController')->middleware('dev');
Route::get('module/create/{tutorial}', 'Dev\ModuleController@create')->name('module.create');
Route::post('module/updatePos', 'Dev\ModuleController@updatePos')->name('module.updatePos');

// Dev Lesson Routes
Route::resource('dev/lesson', 'Dev\LessonController')->middleware('dev');
Route::get('lesson/create/{module}', 'Dev\LessonController@create')->name('lesson.create');
Route::post('lesson/updatePos', 'Dev\LessonController@updatePos')->name('lesson.updatePos');

// Dev Topic Routes
Route::resource('dev/topic', 'Dev\TopicController')->middleware('dev');
Route::get('topic/create/{lesson}', 'Dev\TopicController@create')->name('topic.create');
Route::post('topic/updatePos', 'Dev\TopicController@updatePos')->name('topic.updatePos');

// Dev Question Routes
Route::resource('dev/question', 'Dev\QuestionController');

/* Play Routes */
Route::get('play/{tutorial}', 'PlayController@index')->name('play');
Route::get('play/reset/{tutorial}', 'PlayController@reset_progress')->name('play.reset');

/* Play Ajax Routes */
Route::get('play/tutorial/{tutorial}', 'PlayController@tutorial')->name('play.tutorial');
Route::get('play/module/{module}', 'PlayController@module')->name('play.module');
Route::get('play/lesson/{lesson}', 'PlayController@lesson')->name('play.lesson');
Route::get('play/update_lesson/{lesson}', 'PlayController@update_lesson')->name('update.lesson');

// Profile Routes
Route::get('profil', 'ProfileController@index')->name('profile.index');
Route::patch('profile/update', 'ProfileController@update')->name('profile.update');

// Certificate Routes
Route::get('certificate/{certificate}', 'CertificateController@show')->name('certificate.show');
Route::get('certificate/check/{tutorial}', 'CertificateController@check')->name('certificate.check');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $guarded = [];

    public function lesson()
    {
        return $this->belongsTo(Lesson::class);
    }

    public function question()
    {
        return $this->hasOne(Question::class);
    }
}

app/Http/Controllers/Dev/AnswerController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Answer;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function store($question, $answers)
    {
        foreach ($answers as $answer) {
            Answer::create([
                'question_id' => $question->id,
                'body' => $answer,
            ]);
        }
    }

}

app/Http/Controllers/Dev/LessonController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Lesson;
use App\Module;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-create: Loads lesson create view
 * 2-store: Stores posted request
 * 3-show: Shows a single lesson
 * 4-edit: Loads edit page for selected lesson
 * 5-update: Updates posted request for lesson
 * 6-destroy: Deletes selected lesson
 * 7-validateRequest: Validates post request
 * 8-updatePos: Updates lesson position
 * */

class LessonController extends Controller
{

    public function create(Module $module)
    {
        return view('dev.lesson.create', compact('module'));
    }

    public function store(Request $request)
    {
        $this->valideteRequest();

        $countCurrent = Lesson::where('module_id', $request->module_id)->count();

        Lesson::create([
            'module_id' => $request->module_id,
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        return redirect('dev/module/'.request('module_id'));
    }

    public function show(Lesson $lesson)
    {
        return view('dev.lesson.show', compact('lesson'));
    }

    public function edit(Lesson $lesson)
    {
        return view('dev.lesson.edit', compact('lesson'));
    }

    public function update(Request $request, Lesson $lesson)
    {
        $data = $this->valideteRequest();

        $lesson->update($data);

        return redirect('dev/module/'.request('module_id'));
    }

    public function destroy(Lesson $lesson)
    {
        $lesson->delete();
        return redirect('dev/module/'.$lesson->module->id);
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Lesson::find($position[0])->update(['position' => $position[1]]);
        }
    }

    public function valideteRequest()
    {
        return request()->validate([
            'module_id' => 'required',
            'name' => 'required',
            'position' => '',
        ]);
    }
}

app/Http/Controllers/Dev/ModuleController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Module;
use App\Tutorial;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-create: Loads module create view
 * 2-store: Stores posted request
 * 3-show: Shows a single module
 * 4-edit: Loads edit page for selected module
 * 5-update: Updates posted request for module
 * 6-destroy: Deletes selected module
 * 7-validateRequest: Validates post request
 * 8-storeImg: Stores and resizes image
 * 9-updatePos: Updates module position
 * */

class ModuleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function create(Tutorial $tutorial)
    {
        return view('dev.module.create', compact(['tutorial']));
    }

    public function store(Request $request)
    {
        $this->validateRequest();

        $countCurrent = Module::where('tutorial_id', $request->tutorial_id)->count();

        $module = Module::create([
            'tutorial_id' => $request->tutorial_id,
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        $this->storeImg($module);

        return redirect('dev/module/'.$module->id);
    }

    public function show(Module $module)
    {
        return view('dev.module.show', compact('module'));
    }

    public function edit(Module $module)
    {
        return view('dev.module.edit', compact('module'));
    }

    public function update(Request $request, Module $module)
    {
        $module->update($this->validateRequest());

        $this->storeImg($module);

        return redirect('dev/tutorial/'.request('tutorial_id'));
    }

    public function destroy(Module $module)
    {
        $module->delete();

        return redirect('dev');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required',
            'tutorial_id' => '',
            'icon' => 'sometimes|file|image|max:5000',
            'position' => '',
        ]);

    }

    private function storeImg($module)
    {
        if (request()->has('icon')){
            $module->update([
                'icon' => request()->icon->store('uploads', 'public'),
            ]);
            $image = Image::make(public_path('storage/'.$module->icon))->fit(300, 300);
            $image->save();
        }


    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Module::find($position[0])->update(['position' => $position[1]]);
        }
    }
}

app/Http/Controllers/Dev/QuestionController.php
<?php

namespace App\Http\Controllers\Dev;


use App\Http\Controllers\Controller;
use App\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Dev\AnswerController;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function store($topic, $request)
    {
        $type = $request['question_type'];

        if ($type == 'FILL') {
            $this->createFill($topic, $request);
        } elseif ($type == 'QUIZ'){
            $this->createQuiz($topic, $request);
        } elseif ($type == 'TYPEIN'){
            $this->createTypeIn($topic, $request);
        }
    }

    public function update(Request $request, Question $question)
    {

        $this->validateInfo($request);

        $question->answers()->delete();
        $question->delete();
        $this->store($question->topic, $request);
        return redirect('dev/topic/'.$question->topic->id);

    }

    protected function createFill($topic, $request)
    {
        // Question body
        $string = $request['question_body'];

        // Define pattern
        $pattern = '~<mark>(.*?)</mark>~';

        //Find all matches
        preg_match_all($pattern, $string, $matches);

        // Replace each match with input
        foreach ($matches[1] as $answer) {
            $new_pattern = '~<mark>'.$answer.'</mark>~';
            $replace = '<input type="text" name="qs[]" maxlength="'.strlen($answer).'" size="'.strlen($answer).'" required>';
            $string = preg_replace($new_pattern, $replace, $string);
        }

        //Empty answers array to push
        $answers = [];

        foreach ($matches[1] as $match){
            array_push($answers, $match);
        }

        $question = Question::create([
            'topic_id' => $topic->id,
            'body' => $string,
            'type' => $request->question_type,
        ]);


        // Create answers in DB
        $a = new AnswerController();
        $a->store($question, $answers);

        return true;
    }

    protected function createQuiz($topic, $request)
    {
        $question = Question::create([
            'topic_id' => $topic->id,
            'body' => $request['question_body'],
            'answer' => $request['answer'],
            'type' => $request->question_type,
        ]);

        $a = new AnswerController();
        $a->store($question, $request['answers']);

        return true;
    }

    protected function createTypeIn($topic, $request)
    {
        Question::create([
            'topic_id' => $topic->id,
            'body' => $request['question_body'],
            'answer' => $request['answer'],
            'type' => $request->question_type,
        ]);

        return true;
    }

    protected function validateInfo($request)
    {
        $request->validate([
            'question_body' => 'required',
            'active' => 'min:1',
        ]);

        $type = $request['question_type'];

        if ($type == 'FILL') {
            $request->validate([
                'marked' => 'min:1',
            ]);
        } elseif ($type == 'QUIZ'){
            $request->validate([
                'answer' => 'required',
                'answers' => 'required',
            ]);
        } elseif ($type == 'TYPEIN'){
            $request->validate([
                'answer' => 'required',
            ]);
        }
    }
}

app/Http/Controllers/Dev/TopicController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Dev\QuestionController;
use App\Lesson;
use App\Topic;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TopicController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function create(Lesson $lesson)
    {
        return view('dev.topic.create', compact(['lesson']));
    }

    public function store(Request $request)
    {
        $this->validateRequest($request);

        $countCurrent = Topic::where('lesson_id', $request->lesson_id)->count();

        $topic = Topic::create([
            'lesson_id' => $request['lesson_id'],
            'body' => $request['topic_body'],
            'position' => ($countCurrent + 1),
        ]);

        $q = new QuestionController();
        $q->store($topic, $request);

        return redirect('dev/lesson/'.$topic->lesson->id);
    }

    public function show(Topic $topic)
    {
        return view('dev.topic.show', compact(['topic']));
    }

    public function edit(Topic $topic)
    {
        return view('dev.topic.edit', compact('topic'));
    }

    public function update(Request $request, Topic $topic)
    {
        $data = request()->validate([
            'body' => 'required',
        ]);

        $topic->update($data);

        return redirect('dev/lesson/'.$topic->lesson->id);
    }

    public function destroy(Topic $topic)
    {

        $da = $topic->question->answers()->delete();
        $dq = $topic->question()->delete();
        $dt = $topic->delete();

        if($da && $dq && $da) {
            return redirect('dev/lesson/'.$topic->lesson->id);
        } else {
            return redirect('dev/lesson/'.$topic->lesson->id);
        }

    }

    public function validateRequest($request)
    {

        $request->validate([
            'lesson_id' => 'required',
            'topic_body' => 'required',
            'question_body' => 'required',
            'active' => 'min:1',
            'position' => '',
        ]);

        $type = $request['question_type'];

        if ($type == 'FILL') {
            $request->validate([
                'marked' => 'min:1',
            ]);
        } elseif ($type == 'QUIZ'){
            $request->validate([
                'answer' => 'required',
                'answers' => 'required',
            ]);
        } elseif ($type == 'TYPEIN'){
            $request->validate([
                'answer' => 'required',
            ]);
        }
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Topic::find($position[0])->update(['position' => $position[1]]);
        }
    }

}

app/Http/Controllers/Dev/TutorialController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Tutorial;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-index: Loads all tutorials with view
 * 2-create: Loads tutorial create view
 * 3-store: Stores posted request
 * 4-show: Shows a single tutorial
 * 5-edit: Loads edit page for selected tutorial
 * 6-update: Updates posted request for tutorial
 * 7-destroy: Deletes selected tutorial
 * 8-validateRequest: Validates post request
 * 9-storeImg: Stores and resizes image
 * 10-updatePos: Updates tutorial position
 * */

class TutorialController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function index()
    {
        $tutorials = Tutorial::orderBy('position', 'asc')->get();

        return view('dev.tutorial.index', compact(['tutorials']));
    }

    public function create()
    {
        return view('dev.tutorial.create');
    }

    public function store(Request $request)
    {
        $this->validateRequest();

        $countCurrent = Tutorial::get()->count();

        // TODO Short desc and long desc should be added
        $tutorial = Tutorial::create([
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        $this->storeImg($tutorial);

        return redirect('dev/tutorial/'.$tutorial->id);
    }

    public function show(Tutorial $tutorial)
    {
        return view('dev.tutorial.show', compact(['tutorial']));
    }

    public function edit(Tutorial $tutorial)
    {
        return view('dev.tutorial.edit', compact(['tutorial']));
    }

    public function update(Request $request, Tutorial $tutorial)
    {

        $tutorial->update($this->validateRequest());

        $this->storeImg($tutorial);

        return redirect('dev/tutorial/'.$tutorial->id);
    }

    public function destroy(Tutorial $tutorial)
    {
        $tutorial->delete();

        return redirect('dev');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required',
            'position' => 'sometimes',
            'logo' => 'sometimes|file|image|max:5000',
        ]);

    }

    private function storeImg($tutorial)
    {
        if (request()->has('logo')){
            $tutorial->update([
                'logo' => request()->logo->store('uploads', 'public'),
            ]);
            $image = Image::make(public_path('storage/'.$tutorial->logo))->fit(300, 300);
            $image->save();
        }
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Tutorial::find($position[0])->update(['position' => $position[1]]);
        }
    }

}

app/Http/Controllers/DevController.php
<?php

namespace App\Http\Controllers;

use App\Tutorial;
use App\User;
use Illuminate\Http\Request;

class DevController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function index()
    {
        return view('dev.index');
    }

}

resources/views/dev/topic/create.blade.php
@extends('dev.layouts.app')

@section('title', $lesson->name.'\'e Konu Anlatımı Ekle')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-6">

                <h2>{{ $lesson->name }} - Konu Anlatımı Ekle </h2>
            </div>
            <div class="col-6">
                <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('fill')">
                    <i class="fa fa-outdent"></i>
                </button>
                <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('quiz')">
                    <i class="fa fa-list-ul"></i>
                </button>
                <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('typeIn')">
                    <i class="fa fa-terminal"></i>
                </button>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-12">
                <form action="{{ route('topic.store') }}" method="POST" id="form" onsubmit="return getContent()">
                    @csrf
                    <div class="row">
                        <div class="col-6">
                            <input type="hidden" name="lesson_id" value="{{ $lesson->id }}">
                            <input type="hidden" name="active" id="active" value="">
                            <div class="form-group">
                                <label for="topic_body"><b>KONU</b></label>
                                <textarea rows="20" name="topic_body" class="form-control" id="topic" placeholder="Konu anlatımı içeriği">{{ old('topic_body') }}</textarea>
                                <p><small>{{ $errors->first('body') }}</small></p>
                            </div>
                        </div>
                        <div class="col-6">
                            <input type="hidden" name="lesson_id" value="{{ $lesson->id }}">
                            <label for="question_body"><b>SORU</b></label>
                            <div class="q_outer">
                                <div id="content" contenteditable>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    A, ad fugit maiores optio placeat tenetur totam! Architecto, asperiores dolor facere
                                    incidunt laborum omnis praesentium rem sapiente sunt! Fugiat, illum, ullam?
                                </div>
                                <textarea name="question_body" id="myTextArea" style="display: none;"></textarea>
                            </div>

                            <div id="answers">

                            </div>

                        </div>
                    </div>
                    <hr>
                    <input type="hidden" name="position" value="0">
                    <button type="submit" class="btn btn-primary w-100" id="submit">Ekle</button>
                </form>
            </div>
        </div>
    </div>


    <div id="fill">
        <input type="hidden" name="question_type" value="FILL">
        <input type="hidden" name="marked" id="marked" value="">
        <p class="text-dark pt-3"><b>Cevap olarak kalması gereken yerleri 'MARK' butonuyla işaretleyiniz.</b></p>
        <button type="button" class="btn btn-warning" onclick="mark()">MARK</button>
    </div>

    <div id="quiz">
        <input type="hidden" name="question_type" value="QUIZ">
        <p class="text-dark pt-3"><b>Üç seçenek yazıp doğru cevabı işaretleyiniz</b></p>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="A">
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 1" required>
        </div>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="B">
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 2" required>
        </div>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="C">
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 3" required>
        </div>
    </div>

    <div id="typeIn">
        <input type="hidden" name="question_type" value="TYPEIN">
        <p>Bir soru içeriği ve bir cevap giriniz.</p>
        <div class="form-group">
            <input type="text" name="answer" class="form-control" placeholder="Doğru Cevap" required>
        </div>
    </div>



@endsection

@section('js')
    <script>tinymce.init({selector:'#topic'});</script>
@endsection

resources/views/dev/topic/edit.blade.php
@extends('dev.layouts.app')

@section('title', $topic->lesson->name.'\'e Konu Anlatımı Düzenle')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-6">
                <h2>{{ $topic->lesson->name }} - Konu Anlatımı Düzenle </h2>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-12">
                <form action="{{ route('topic.update', ['topic' => $topic]) }}" method="POST"->
                    @csrf
                    @method('PATCH')
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="body"><b>KONU</b></label>
                                <textarea rows="20" name="body" class="form-control" id="topic">{{ old('topic_body') ?? $topic->body }}</textarea>
                                <p class="text-danger"><b>{{ $errors->first('body') }}</b></p>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">KAYDET</button>
                </form>
            </div>
        </div>
    </div>


@endsection

@section('js')
    <script>tinymce.init({selector:'#topic'});</script>
@endsection

resources/views/dev/topic/show.blade.php
@extends('dev.layouts.app')

@section('title', $topic->name)

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-6 card">
                <div class="card-header d-flex justify-content-between">
                    <p><b>KONU</b></p>
                    <div class="d-flex">
                        <a href="{{ route('topic.edit', ['topic' => $topic]) }}" class="btn btn-outline-info"><i class="fa fa-edit"></i></a>
                        <form action="{{ route('topic.destroy', ['topic' => $topic]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-outline-danger ml-2"><i class="fa fa-trash"></i></button>
                        </form>
                    </div>
                </div>
                <div class="card-body">
                    <div><?= $topic->body ?></div>
                </div>
            </div>
            <div class="col-6 card">
                <div class="card-header d-flex justify-content-between questionHeader">
                    <p><b>SORU</b></p>
                    <button type="button" class="btn btn-outline-danger" onclick="questionDelete()"><i class="fa fa-trash"></i></button>
                </div>
                <div class="card-body questionBody">
                    <?php echo $topic->question->body; ?>
                    <hr>
                    <p><b>Cevaplar:</b></p>
                    <ol type="a">
                        @foreach($topic->question->answers as $answer)
                            <li>{{ $answer->body }}</li>
                        @endforeach
                    </ol>
                    @if($topic->question->answer)
                        <p><b>Doğru cevap:</b> <mark>{{ $topic->question->answer }}</mark></p>
                    @endif
                </div>

                <p class="text-danger"><small>{{ $errors->first('question_body') }}</small></p>
                <p class="text-danger"><small>{{ $errors->first('active') }}</small></p>
                <p class="text-danger"><small>{{ $errors->first('marked') }}</small></p>
                <p class="text-danger"><small>{{ $errors->first('answer') }}</small></p>
                <p class="text-danger"><small>{{ $errors->first('answers') }}</small></p>
            </div>
        </div>
    </div>

    <div class="buttons" style="display: none;">
        <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('fill')">
            <i class="fa fa-outdent"></i>
        </button>
        <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('quiz')">
            <i class="fa fa-list-ul"></i>
        </button>
        <button type="button" class="btn btn-lg btn-outline-dark" onclick="showQ('typeIn')">
            <i class="fa fa-terminal"></i>
        </button>
    </div>

    <div id="formBody"  style="display: none;">
        <form action="{{ route('question.update', ['question' => $topic->question]) }}" method="POST" id="form" onsubmit="return getContent()">
            @csrf
            @method('PATCH')
            <input type="hidden" name="active" id="active">
            <div class="q_outer">
                <div id="content" contenteditable>
                    {{ old('question_body') }}
                </div>
                <textarea name="question_body" id="myTextArea" style="display: none;"   ></textarea>
            </div>

            <div id="answers">

            </div>

            <hr>
            <button type="submit" class="btn btn-primary w-100" id="submit">Ekle</button>
        </form>
    </div>


    <div id="fill">
        <input type="hidden" name="question_type" value="1">
        <input type="hidden" name="marked" id="marked">
        <p class="text-dark pt-3"><b>Cevap olarak kalması gereken yerleri 'MARK' butonuyla işaretleyiniz.</b></p>
        <button type="button" class="btn btn-warning" onclick="mark()">MARK</button>
    </div>

    <div id="quiz">
        <input type="hidden" name="question_type" value="2">
        <p class="text-dark pt-3"><b>Üç seçenek yazıp doğru cevabı işaretleyiniz</b></p>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="a" required>
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 1" required>
        </div>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="b">
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 2" required>
        </div>

        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="answer" value="c">
            </div>
            <input type="text" name="answers[]" class="form-control" placeholder="Seçenek 3" required>
        </div>
    </div>

    <div id="typeIn">
        <input type="hidden" name="question_type" value="3">
        <p>Bir soru içeriği ve bir cevap giriniz.</p>
        <div class="form-group">
            <input type="text" name="answer" class="form-control" placeholder="Doğru Cevap" required>
        </div>
    </div>


@endsection