routes/web.php
<?php


Auth::routes();

// Home routes
Route::get('/', 'HomeController@index')->name('home');
Route::get('kurslar', 'HomeController@courses')->name('courses');
Route::get('kurs/{tutorial}', 'HomeController@course')->name('course');
Route::get('home/emailSub', 'HomeController@emailSub')->name('home.emailSub');

/* Dev Panel Routes */
Route::get('dev', 'DevController@index')->name('dev.index');

// Dev Tutorial Routes
Route::resource('dev/tutorial', 'Dev\TutorialController');
Route::post('tutorial/updatePos', 'Dev\TutorialController@updatePos')->name('tutorial.updatePos');

// Dev Module Routes
Route::resource('dev/module', 'Dev\ModuleController')->middleware('dev');
Route::get('module/create/{tutorial}', 'Dev\ModuleController@create')->name('module.create');
Route::post('module/updatePos', 'Dev\ModuleController@updatePos')->name('module.updatePos');

// Dev Lesson Routes
Route::resource('dev/lesson', 'Dev\LessonController')->middleware('dev');
Route::get('lesson/create/{module}', 'Dev\LessonController@create')->name('lesson.create');
Route::post('lesson/updatePos', 'Dev\LessonController@updatePos')->name('lesson.updatePos');

// Dev Topic Routes
Route::resource('dev/topic', 'Dev\TopicController')->middleware('dev');
Route::get('topic/create/{lesson}', 'Dev\TopicController@create')->name('topic.create');
Route::post('topic/updatePos', 'Dev\TopicController@updatePos')->name('topic.updatePos');

// Dev Question Routes
Route::resource('dev/question', 'Dev\QuestionController');

/* Play Routes */
Route::get('play/{tutorial}', 'PlayController@index')->name('play');
Route::get('play/reset/{tutorial}', 'PlayController@reset_progress')->name('play.reset');

/* Play Ajax Routes */
Route::get('play/tutorial/{tutorial}', 'PlayController@tutorial')->name('play.tutorial');
Route::get('play/module/{module}', 'PlayController@module')->name('play.module');
Route::get('play/lesson/{lesson}', 'PlayController@lesson')->name('play.lesson');
Route::get('play/update_lesson/{lesson}', 'PlayController@update_lesson')->name('update.lesson');

// Profile Routes
Route::get('profil', 'ProfileController@index')->name('profile.index');
Route::patch('profile/update', 'ProfileController@update')->name('profile.update');

// Certificate Routes
Route::get('certificate/{certificate}', 'CertificateController@show')->name('certificate.show');
Route::get('certificate/check/{tutorial}', 'CertificateController@check')->name('certificate.check');

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    protected $guarded = [];

    public function module()
    {
        return $this->belongsTo(Module::class);
    }

    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    public function users()
    {
        return $this->belongsToMany(\App\User::class)->withPivot(['status'])->withTimestamps();
    }
}

app/Http/Controllers/Dev/AnswerController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Answer;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function store($question, $answers)
    {
        foreach ($answers as $answer) {
            Answer::create([
                'question_id' => $question->id,
                'body' => $answer,
            ]);
        }
    }

}

app/Http/Controllers/Dev/LessonController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Lesson;
use App\Module;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-create: Loads lesson create view
 * 2-store: Stores posted request
 * 3-show: Shows a single lesson
 * 4-edit: Loads edit page for selected lesson
 * 5-update: Updates posted request for lesson
 * 6-destroy: Deletes selected lesson
 * 7-validateRequest: Validates post request
 * 8-updatePos: Updates lesson position
 * */

class LessonController extends Controller
{

    public function create(Module $module)
    {
        return view('dev.lesson.create', compact('module'));
    }

    public function store(Request $request)
    {
        $this->valideteRequest();

        $countCurrent = Lesson::where('module_id', $request->module_id)->count();

        Lesson::create([
            'module_id' => $request->module_id,
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        return redirect('dev/module/'.request('module_id'));
    }

    public function show(Lesson $lesson)
    {
        return view('dev.lesson.show', compact('lesson'));
    }

    public function edit(Lesson $lesson)
    {
        return view('dev.lesson.edit', compact('lesson'));
    }

    public function update(Request $request, Lesson $lesson)
    {
        $data = $this->valideteRequest();

        $lesson->update($data);

        return redirect('dev/module/'.request('module_id'));
    }

    public function destroy(Lesson $lesson)
    {
        $lesson->delete();
        return redirect('dev/module/'.$lesson->module->id);
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Lesson::find($position[0])->update(['position' => $position[1]]);
        }
    }

    public function valideteRequest()
    {
        return request()->validate([
            'module_id' => 'required',
            'name' => 'required',
            'position' => '',
        ]);
    }
}

app/Http/Controllers/Dev/ModuleController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Module;
use App\Tutorial;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-create: Loads module create view
 * 2-store: Stores posted request
 * 3-show: Shows a single module
 * 4-edit: Loads edit page for selected module
 * 5-update: Updates posted request for module
 * 6-destroy: Deletes selected module
 * 7-validateRequest: Validates post request
 * 8-storeImg: Stores and resizes image
 * 9-updatePos: Updates module position
 * */

class ModuleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function create(Tutorial $tutorial)
    {
        return view('dev.module.create', compact(['tutorial']));
    }

    public function store(Request $request)
    {
        $this->validateRequest();

        $countCurrent = Module::where('tutorial_id', $request->tutorial_id)->count();

        $module = Module::create([
            'tutorial_id' => $request->tutorial_id,
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        $this->storeImg($module);

        return redirect('dev/module/'.$module->id);
    }

    public function show(Module $module)
    {
        return view('dev.module.show', compact('module'));
    }

    public function edit(Module $module)
    {
        return view('dev.module.edit', compact('module'));
    }

    public function update(Request $request, Module $module)
    {
        $module->update($this->validateRequest());

        $this->storeImg($module);

        return redirect('dev/tutorial/'.request('tutorial_id'));
    }

    public function destroy(Module $module)
    {
        $module->delete();

        return redirect('dev');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required',
            'tutorial_id' => '',
            'icon' => 'sometimes|file|image|max:5000',
            'position' => '',
        ]);

    }

    private function storeImg($module)
    {
        if (request()->has('icon')){
            $module->update([
                'icon' => request()->icon->store('uploads', 'public'),
            ]);
            $image = Image::make(public_path('storage/'.$module->icon))->fit(300, 300);
            $image->save();
        }


    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Module::find($position[0])->update(['position' => $position[1]]);
        }
    }
}

app/Http/Controllers/Dev/QuestionController.php
<?php

namespace App\Http\Controllers\Dev;


use App\Http\Controllers\Controller;
use App\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Dev\AnswerController;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function store($topic, $request)
    {
        $type = $request['question_type'];

        if ($type == 'FILL') {
            $this->createFill($topic, $request);
        } elseif ($type == 'QUIZ'){
            $this->createQuiz($topic, $request);
        } elseif ($type == 'TYPEIN'){
            $this->createTypeIn($topic, $request);
        }
    }

    public function update(Request $request, Question $question)
    {

        $this->validateInfo($request);

        $question->answers()->delete();
        $question->delete();
        $this->store($question->topic, $request);
        return redirect('dev/topic/'.$question->topic->id);

    }

    protected function createFill($topic, $request)
    {
        // Question body
        $string = $request['question_body'];

        // Define pattern
        $pattern = '~<mark>(.*?)</mark>~';

        //Find all matches
        preg_match_all($pattern, $string, $matches);

        // Replace each match with input
        foreach ($matches[1] as $answer) {
            $new_pattern = '~<mark>'.$answer.'</mark>~';
            $replace = '<input type="text" name="qs[]" maxlength="'.strlen($answer).'" size="'.strlen($answer).'" required>';
            $string = preg_replace($new_pattern, $replace, $string);
        }

        //Empty answers array to push
        $answers = [];

        foreach ($matches[1] as $match){
            array_push($answers, $match);
        }

        $question = Question::create([
            'topic_id' => $topic->id,
            'body' => $string,
            'type' => $request->question_type,
        ]);


        // Create answers in DB
        $a = new AnswerController();
        $a->store($question, $answers);

        return true;
    }

    protected function createQuiz($topic, $request)
    {
        $question = Question::create([
            'topic_id' => $topic->id,
            'body' => $request['question_body'],
            'answer' => $request['answer'],
            'type' => $request->question_type,
        ]);

        $a = new AnswerController();
        $a->store($question, $request['answers']);

        return true;
    }

    protected function createTypeIn($topic, $request)
    {
        Question::create([
            'topic_id' => $topic->id,
            'body' => $request['question_body'],
            'answer' => $request['answer'],
            'type' => $request->question_type,
        ]);

        return true;
    }

    protected function validateInfo($request)
    {
        $request->validate([
            'question_body' => 'required',
            'active' => 'min:1',
        ]);

        $type = $request['question_type'];

        if ($type == 'FILL') {
            $request->validate([
                'marked' => 'min:1',
            ]);
        } elseif ($type == 'QUIZ'){
            $request->validate([
                'answer' => 'required',
                'answers' => 'required',
            ]);
        } elseif ($type == 'TYPEIN'){
            $request->validate([
                'answer' => 'required',
            ]);
        }
    }
}

app/Http/Controllers/Dev/TopicController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Dev\QuestionController;
use App\Lesson;
use App\Topic;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TopicController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function create(Lesson $lesson)
    {
        return view('dev.topic.create', compact(['lesson']));
    }

    public function store(Request $request)
    {
        $this->validateRequest($request);

        $countCurrent = Topic::where('lesson_id', $request->lesson_id)->count();

        $topic = Topic::create([
            'lesson_id' => $request['lesson_id'],
            'body' => $request['topic_body'],
            'position' => ($countCurrent + 1),
        ]);

        $q = new QuestionController();
        $q->store($topic, $request);

        return redirect('dev/lesson/'.$topic->lesson->id);
    }

    public function show(Topic $topic)
    {
        return view('dev.topic.show', compact(['topic']));
    }

    public function edit(Topic $topic)
    {
        return view('dev.topic.edit', compact('topic'));
    }

    public function update(Request $request, Topic $topic)
    {
        $data = request()->validate([
            'body' => 'required',
        ]);

        $topic->update($data);

        return redirect('dev/lesson/'.$topic->lesson->id);
    }

    public function destroy(Topic $topic)
    {

        $da = $topic->question->answers()->delete();
        $dq = $topic->question()->delete();
        $dt = $topic->delete();

        if($da && $dq && $da) {
            return redirect('dev/lesson/'.$topic->lesson->id);
        } else {
            return redirect('dev/lesson/'.$topic->lesson->id);
        }

    }

    public function validateRequest($request)
    {

        $request->validate([
            'lesson_id' => 'required',
            'topic_body' => 'required',
            'question_body' => 'required',
            'active' => 'min:1',
            'position' => '',
        ]);

        $type = $request['question_type'];

        if ($type == 'FILL') {
            $request->validate([
                'marked' => 'min:1',
            ]);
        } elseif ($type == 'QUIZ'){
            $request->validate([
                'answer' => 'required',
                'answers' => 'required',
            ]);
        } elseif ($type == 'TYPEIN'){
            $request->validate([
                'answer' => 'required',
            ]);
        }
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Topic::find($position[0])->update(['position' => $position[1]]);
        }
    }

}

app/Http/Controllers/Dev/TutorialController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Tutorial;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

/*
 * 0-construct: checks for if user authorized and a developer
 * 1-index: Loads all tutorials with view
 * 2-create: Loads tutorial create view
 * 3-store: Stores posted request
 * 4-show: Shows a single tutorial
 * 5-edit: Loads edit page for selected tutorial
 * 6-update: Updates posted request for tutorial
 * 7-destroy: Deletes selected tutorial
 * 8-validateRequest: Validates post request
 * 9-storeImg: Stores and resizes image
 * 10-updatePos: Updates tutorial position
 * */

class TutorialController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function index()
    {
        $tutorials = Tutorial::orderBy('position', 'asc')->get();

        return view('dev.tutorial.index', compact(['tutorials']));
    }

    public function create()
    {
        return view('dev.tutorial.create');
    }

    public function store(Request $request)
    {
        $this->validateRequest();

        $countCurrent = Tutorial::get()->count();

        // TODO Short desc and long desc should be added
        $tutorial = Tutorial::create([
            'name' => $request->name,
            'position' => ($countCurrent + 1),
        ]);

        $this->storeImg($tutorial);

        return redirect('dev/tutorial/'.$tutorial->id);
    }

    public function show(Tutorial $tutorial)
    {
        return view('dev.tutorial.show', compact(['tutorial']));
    }

    public function edit(Tutorial $tutorial)
    {
        return view('dev.tutorial.edit', compact(['tutorial']));
    }

    public function update(Request $request, Tutorial $tutorial)
    {

        $tutorial->update($this->validateRequest());

        $this->storeImg($tutorial);

        return redirect('dev/tutorial/'.$tutorial->id);
    }

    public function destroy(Tutorial $tutorial)
    {
        $tutorial->delete();

        return redirect('dev');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required',
            'position' => 'sometimes',
            'logo' => 'sometimes|file|image|max:5000',
        ]);

    }

    private function storeImg($tutorial)
    {
        if (request()->has('logo')){
            $tutorial->update([
                'logo' => request()->logo->store('uploads', 'public'),
            ]);
            $image = Image::make(public_path('storage/'.$tutorial->logo))->fit(300, 300);
            $image->save();
        }
    }

    public function updatePos()
    {
        foreach ($_POST['positions'] as $position) {
            Tutorial::find($position[0])->update(['position' => $position[1]]);
        }
    }

}

app/Http/Controllers/DevController.php
<?php

namespace App\Http\Controllers;

use App\Tutorial;
use App\User;
use Illuminate\Http\Request;

class DevController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('dev');
    }

    public function index()
    {
        return view('dev.index');
    }

}

resources/views/dev/lesson/create.blade.php
@extends('dev.layouts.app')

@section('title', $module->name.' Modülüne Ders Ekle')

@section('content')
    <div class="container">
            <h2>{{ $module->name }} Modülüne Ders Ekle</h2>
            <form action="{{ route('lesson.store') }}" method="POST">
                @csrf
                <input type="hidden" name="module_id" value="{{ $module->id }}">
                <div class="form-group">
                    <input type="text" name="name" class="form-control" placeholder="Ders ismi" required>
                    <p><small>{{ $errors->first('name') }}</small></p>
                </div>
                <input type="hidden" name="position" value="0">
                <button type="submit" class="btn btn-primary">Ekle</button>
            </form>
    </div>
@endsection

resources/views/dev/lesson/edit.blade.php
@extends('dev.layouts.app')

@section('title', $lesson->name.' Dersi Düzenleniyor')

@section('content')
    <div class="container">
        <h2>{{ $lesson->name }} Dersi Düzenle</h2>
        <form action="{{ route('lesson.update', ['lesson' => $lesson]) }}" method="POST">
            @csrf
            @method('PATCH')
            <input type="hidden" name="module_id" value="{{ $lesson->module->id }}">
            <div class="form-group">
                <input type="text" name="name" value="{{ $lesson->name }}" class="form-control" placeholder="Ders ismi" required>
                <p><small>{{ $errors->first('name') }}</small></p>
            </div>
            <button type="submit" class="btn btn-primary">Düzenle</button>
        </form>
    </div>
@endsection

resources/views/dev/lesson/show.blade.php
@extends('dev.layouts.app')

@section('title', $lesson->name.' Dersi')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-2">
                <h2>{{ $lesson->name }}</h2>
                <p>
                    <b>Modül: </b>
                    <a href="{{ route('module.show', ['module' => $lesson->module]) }}">
                        {{ $lesson->module->name }}
                    </a>
                </p>
                <p><a href="{{ route('lesson.edit', ['lesson' => $lesson]) }}" class="btn btn-info">Düzenle</a></p>
                <form action="{{ route('lesson.destroy', ['lesson' => $lesson]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="button" onclick="if(confirm('Silmek istiyor musun?')){$(this).parent().submit()}"
                            class="btn btn-danger">Sil</button>
                </form>
            </div>
            <div class="col-md-8 mb-2">
                <h3>Konu Anlatımları</h3>
                <p>
                    <a href="{{ route('topic.create', ['lesson' => $lesson]) }}" class="btn btn-sm btn-outline-secondary">
                        Yeni Konu Anlatımı
                    </a>
                </p>

                <table>
                    <tbody>
                        @foreach($lesson->topics()->orderBy('position', 'asc')->get() as $topic)
                            <tr data-index="{{ $topic->id }}" data-position="{{ $topic->position }}">
                                <td>
                                    <a href="{{ route('topic.show', ['topic' => $topic]) }}">
                                        {{ $topic->position .' - '. substr(strip_tags($topic->body), 0, 40) . '...' }}
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function () {
            $('table tbody').sortable({
                update: function (event, ui) {
                    $(this).children().each(function (index) {
                        if($(this).attr('data-position') != (index+1)) {
                            $(this).attr('data-position', (index+1)).addClass('updated');
                        }
                    });

                    saveNewPositions();
                }
            });

        });

        function saveNewPositions() {
            var positions = [];
            $('.updated').each(function () {
                positions.push([$(this).attr('data-index'), $(this).attr('data-position')]);
                $(this).removeClass('updated');
            });

            $.ajax({
                url: '{{ route('topic.updatePos') }}',
                method: 'post',
                dataType: 'text',
                data: {
                    update: 1,
                    positions: positions,
                    _token: '{{csrf_token()}}',
                }, success: function (response) {
                    console.log(response);
                }
            });
        }
    </script>
@endsection